version: '3.9'

services:
  postgres_auth:
    image: postgres:15
    container_name: postgres-auth
    restart: always
    environment:
      POSTGRES_DB: ChatApp_Auth       
      POSTGRES_USER: user          
      POSTGRES_PASSWORD: user  
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - chatapp_network

volumes:
  postgres_auth_data:

networks:
  chatapp_network:
    driver: bridge
